// Module imports
import type { Metadata } from 'next'
import { PropsWithChildren } from 'react'





// Types
type Props = PropsWithChildren





// Constants
export const metadata: Metadata = {
	title: 'Create Next App',
	description: 'Generated by create next app',
}




/**
 * The root layout for the site.
 *
 * @component
 */
export default function RootLayout(props: Props) {
	const { children } = props

	return (
		<html lang='en'>
			<body>
				{children}
			</body>
		</html>
	)
}
